--
-- PostgreSQL database dump
--

\restrict Pn8YBYYJbFET4hMnohWqoWYf9fVkckNDlJzgrYWXXnTdj2n1A7Rm4bB8OgbVFiA

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: characters; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.characters (
    base_hp integer NOT NULL,
    heavy_attack_dmg integer NOT NULL,
    light_attack_dmg integer NOT NULL,
    special_attack_dmg integer NOT NULL,
    char_id bigint NOT NULL,
    heavy_attack_name character varying(255),
    light_attack_name character varying(255),
    name character varying(255) NOT NULL,
    special_attack_name character varying(255),
    type character varying(255) NOT NULL
);


ALTER TABLE public.characters OWNER TO postgres;

--
-- Name: characters_char_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.characters ALTER COLUMN char_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.characters_char_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: enemies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.enemies (
    basic_attack_damage integer NOT NULL,
    heavy_attack_damage integer NOT NULL,
    max_hp integer NOT NULL,
    skill_damage integer NOT NULL,
    stage_id integer NOT NULL,
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.enemies OWNER TO postgres;

--
-- Name: enemies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.enemies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enemies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: game_runs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.game_runs (
    bonus_basic_dmg integer NOT NULL,
    bonus_max_energy integer NOT NULL,
    bonus_max_hp integer NOT NULL,
    bonus_skill_dmg integer NOT NULL,
    current_stage integer NOT NULL,
    death_count integer NOT NULL,
    final_rating integer,
    has_midboss_skill boolean NOT NULL,
    time_elapsed integer NOT NULL,
    char_id bigint NOT NULL,
    run_id uuid NOT NULL,
    user_id uuid NOT NULL,
    status character varying(255)
);


ALTER TABLE public.game_runs OWNER TO postgres;

--
-- Name: players; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.players (
    base_damage integer NOT NULL,
    max_energy integer NOT NULL,
    max_hp integer NOT NULL,
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.players OWNER TO postgres;

--
-- Name: players_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.players ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.players_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    created_at timestamp(6) without time zone,
    user_id uuid NOT NULL,
    password_hash character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Data for Name: characters; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.characters (base_hp, heavy_attack_dmg, light_attack_dmg, special_attack_dmg, char_id, heavy_attack_name, light_attack_name, name, special_attack_name, type) FROM stdin;
90	28	12	50	1	Heavy Slash	Basic Strike	Kael	Ultimate Skill	PLAYER
105	22	9	40	2	Shun Goku Satsu	Hadoken	Ryu	Ryu's Fury	PLAYER
\.


--
-- Data for Name: enemies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.enemies (basic_attack_damage, heavy_attack_damage, max_hp, skill_damage, stage_id, id, name) FROM stdin;
15	30	100	50	1	1	Mr. Van
25	40	120	60	2	2	Mr. Van Stage 2
30	45	130	65	3	3	Mr. Van Stage 3
20	40	150	65	2	4	Chen Long
28	55	220	90	3	5	Kagetsu
35	50	140	70	4	6	Mr. Van Stage 4
35	70	300	120	4	7	Joe
\.


--
-- Data for Name: game_runs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.game_runs (bonus_basic_dmg, bonus_max_energy, bonus_max_hp, bonus_skill_dmg, current_stage, death_count, final_rating, has_midboss_skill, time_elapsed, char_id, run_id, user_id, status) FROM stdin;
0	0	0	0	1	0	\N	f	0	1	e79b166a-6047-42d0-b73f-d811844f40d5	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	1	692732e6-715b-4a5e-bf07-1d1d987d4b7a	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	1	aac76886-2cfe-4931-8c37-aa67b9dfb1b2	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	1	e459d65c-bf6f-4212-90d7-a35a2dfdf917	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	1	16f77a64-15cd-4ec3-9e31-8438ded7ba27	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	1	2aeaca66-fedb-4ac6-8d0a-54d44d6baf92	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	1	5b8be309-7155-44ee-b95a-3c3809409266	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	1	bf526b51-9bec-4108-ac95-2e1b0e164e5e	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	1	031ae8a7-6377-4d54-ba4b-70c108bd5275	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	1	c0319698-b0b0-4e54-95b6-71e823e30ea0	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	1	315b1675-1cef-4946-b5e6-09d9c516dad2	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	1	b91e9c1c-9a9c-44a1-8bfe-f440f01e3fbf	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	2	060178fb-52c1-4c51-a873-84e0fac76f96	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
5	0	0	0	2	0	\N	f	0	1	3153d0a8-67ae-41a6-bfff-602bc06710bf	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
15	0	0	0	4	0	\N	f	0	1	dc30b3d6-c870-4344-8ede-723625674f41	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	7	0	4	2	0	\N	f	0	1	b7d0cfa8-d256-4b8e-a1cc-64d18303f9b9	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	20	0	2	0	\N	f	0	1	ebb6a321-de7e-4465-ba7d-7fa9da9467bd	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	20	0	2	0	\N	f	0	1	950e8b39-46f0-4ee1-bfaf-2a9c602c9f45	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	1	adb4b9a5-d30b-49d6-94ca-3e34643b4669	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	1	67b90833-4755-4b26-8dbf-7aee6cdf9d79	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	1	7a035b10-dfe5-4cee-aec4-63725d01d30e	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	1	e72459c0-ab71-46ff-a21c-268ea30c5f5a	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	20	0	2	0	\N	f	0	1	bebb00fe-bf7e-4cef-8af8-267ee153843b	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	2	e15c8808-1461-4bc7-ba5f-7859d1355ab5	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
5	0	0	0	2	0	\N	f	0	1	7befff92-2993-4b06-ba0f-fb547d4f99a9	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	1	2d5aef83-5914-4125-9a58-7844078ffaca	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	2	fcc8675e-8772-4435-afb6-9d0981dfdf5d	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
5	0	20	0	3	0	\N	f	0	1	ed9c69f6-7fb2-4e9e-a6a3-a6e2522c6a8e	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	7	40	4	4	6	\N	f	136	1	d7aa9ca9-cfcf-4547-b6ac-81ab166efb38	b291084f-c73e-45c6-9085-a2ce7b73fbf1	COMPLETED
0	0	20	0	2	0	\N	f	0	1	5199dc57-a48b-49df-8640-7eee369cc515	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	20	0	2	0	\N	f	0	1	94ebbb54-36c6-49a1-827f-50835ce00a5e	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	2	b13b7fb7-366c-4f98-9277-9b6b4810ef7d	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
5	0	20	0	3	0	\N	f	0	1	e04e2a99-0af5-47c8-888c-13abc44b0cca	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	20	0	2	0	\N	f	0	2	01c6096e-57ca-4e47-a448-c9414c36d5ea	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
5	7	20	4	4	0	\N	f	0	1	a7ba9944-59ad-44f2-a567-6433cc6e332c	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	20	0	2	0	\N	f	0	2	63d899ac-bb6f-429f-9e86-50924a8f2362	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	20	0	2	0	\N	f	0	1	069902f3-9aff-4bab-bb84-28a1d7a235ce	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	2	c1d44d5b-d00f-4015-952e-00b9c2b926d0	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	2	629c43e7-cda9-486b-9c96-267a822d4a76	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	2	f3b3cffa-9493-4466-acc6-aa4fe000ff0e	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	2	6d44d73d-1df7-4e11-a71b-76728549f2aa	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	2	8244c959-683d-4d14-b7ab-e1ea33bac89b	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	2	0b131711-91e1-492a-aa10-63da2754d51b	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	1	81465c9a-4700-41b6-89f9-7f7384790526	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	20	0	2	0	\N	f	0	2	19234628-5e84-40dd-b57e-992fc5ffe4a5	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
5	0	40	0	4	8	\N	f	39	2	b2b0754d-8572-4f3c-8328-361c41997d37	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	40	0	3	0	\N	f	0	2	d3a0eaac-ccd5-4b79-a905-f5da2ac665ba	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	60	0	4	22	\N	f	63	1	efd91ac1-8ce2-456e-84dc-7f5d75fb23e4	b291084f-c73e-45c6-9085-a2ce7b73fbf1	COMPLETED
0	0	0	0	1	0	\N	f	2	2	96c907f5-7fc4-492b-be4b-661e20615eed	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	40	0	3	1	\N	f	31	2	84cf6368-bd6a-4521-bd8e-480fa0c9383a	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	20	0	2	1	\N	f	21	2	93f1ff2a-0fb6-4cfa-a423-578e90dab66d	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	20	0	2	1	\N	f	10	2	53e728ac-f586-4c93-b839-1d70585de090	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	2	c6093253-0da1-4463-b10b-1a2e1e9f7bdd	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	2	333eabff-39fa-4440-9506-f7b02cf265fe	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	0	\N	f	0	2	f2fa6fd5-c1ac-4c86-a3d9-ff6ec32dd1e0	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	0	0	1	1	\N	f	8	2	d793d32f-22c2-426c-8768-b7718ca0699b	b291084f-c73e-45c6-9085-a2ce7b73fbf1	GAME_OVER
0	0	60	0	4	10	\N	f	71	2	328a0fe4-53ff-411a-ab89-0afb55899d6e	b291084f-c73e-45c6-9085-a2ce7b73fbf1	COMPLETED
0	0	60	0	4	8	\N	f	49	2	bb1c30a8-282c-4857-9a40-368620caba42	b291084f-c73e-45c6-9085-a2ce7b73fbf1	COMPLETED
0	0	60	0	4	1	\N	f	160249	2	4af51630-72c0-4d9c-bb76-0f561042333e	b291084f-c73e-45c6-9085-a2ce7b73fbf1	COMPLETED
\.


--
-- Data for Name: players; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.players (base_damage, max_energy, max_hp, id, name) FROM stdin;
10	100	90	1	Kael The Phantom
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (created_at, user_id, password_hash, username) FROM stdin;
2026-05-09 15:21:02.803183	b291084f-c73e-45c6-9085-a2ce7b73fbf1	234567	Huhuyyy
2026-05-09 15:26:39.208084	635a8a90-43ff-4d83-a1ac-200a26bc8a11	test123	test
2026-05-24 11:22:43.549693	b1e412ea-f35f-40ee-86f0-3dea6a4f8dfb	9	ararkyu
\.


--
-- Name: characters_char_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.characters_char_id_seq', 2, true);


--
-- Name: enemies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.enemies_id_seq', 7, true);


--
-- Name: players_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.players_id_seq', 1, true);


--
-- Name: characters characters_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.characters
    ADD CONSTRAINT characters_pkey PRIMARY KEY (char_id);


--
-- Name: enemies enemies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enemies
    ADD CONSTRAINT enemies_pkey PRIMARY KEY (id);


--
-- Name: game_runs game_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_runs
    ADD CONSTRAINT game_runs_pkey PRIMARY KEY (run_id);


--
-- Name: players players_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.players
    ADD CONSTRAINT players_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: game_runs fked8ovun8e6rg5kp0w15rl40j0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_runs
    ADD CONSTRAINT fked8ovun8e6rg5kp0w15rl40j0 FOREIGN KEY (char_id) REFERENCES public.characters(char_id);


--
-- Name: game_runs fkpn7776xpv1w4460mxbqqri1pa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.game_runs
    ADD CONSTRAINT fkpn7776xpv1w4460mxbqqri1pa FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- PostgreSQL database dump complete
--

\unrestrict Pn8YBYYJbFET4hMnohWqoWYf9fVkckNDlJzgrYWXXnTdj2n1A7Rm4bB8OgbVFiA

