spring.application.name=backend

# Koneksi ke PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/risetobechampion
spring.datasource.username=postgres
spring.datasource.password=01092006
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ddl-auto (update = create/update tables, preserve data)
spring.jpa.hibernate.ddl-auto=update

# Tampilkan query SQL di console untuk memudahkan debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect