spring.application.name=backend

# konfigurasi port (railway butuh ini)
server.port=${PORT:8080}

# koneksi ke postgresql (railway sediakan variabel PGHOST, PGPORT, dll)
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:risetobechampion}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:01092006}
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate ddl-auto (update = create/update tables, preserve data)
spring.jpa.hibernate.ddl-auto=update

# tampilkan query sql di console untuk debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true